
import "./globals.css";
import { Roboto_Slab } from "next/font/google";

const roboto = Roboto_Slab({ subsets: ['latin'], weight: ["300", "400", "600"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  )
}
